# 데이터 프레임 기초

****

**발표자**  
DSC 박소희

**내용**  
1. Pandas 데이터 프레임 생성
2. 데이터 저장
3. 데이터 불러오기
4. 변수 접근
5. 데이터 변환

**데이터 셋**  
lapis_korea.csv

In [1]:
import pandas as pd

'1.5.3'

# 데이터 생성

****

```python
pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)

```

|이름|생년월일|나이|MBTI|
|:--:|:--:|:--:|:--:|
|소희|1995-12-20|28|ENFP|
|영수|2001-06-10|22|ISTP|

**1. 정보를 위와 같은 테이블을 본인 정보와 오른쪽 친구의 정보를 사용하여 생성해봅시다.**  
* Hint: Dictionary 형태로 만들어 team이라는 변수에 저장 후 출력해보세요.

In [10]:
# 아래에 코드를 수정 후 실행해 보세요
team={'이름':['name1','name2'],
      '생년월일':['0000-00-00','0000-00-00'],
      '나이':[00, 00],
      'MBTI':['MBTI1','MBTI2']}

In [11]:
# team 변수를 아래에 출력해보세요
team

{'이름': ['name1', 'name2'],
 '생년월일': ['0000-00-00', '0000-00-00'],
 '나이': [0, 0],
 'MBTI': ['MBTI1', 'MBTI2']}

**2. team 변수를 데이터프레임으로 만든 후 team_df 변수로 저장하여 출력하시오.**  
* Hint: pd.DataFrame을 활용해봅시다.

In [ ]:
# 아래에 코드를 작성 후 실행해 보세요
team_df = pd.DataFrame(team)
team_df

**3. team_df 변수에 학생1, 학생2라는 인덱스를 추가해주세요.**  
* Hint: pd.DataFrame의 index 옵션을 활용해봅시다.

In [ ]:
# team이라는 Dictionary 변수에 학생1, 학생2라는 인덱스를 추가하여 데이터프레임으로 만들어주세요
pd.DataFrame(team, index=['index1','index2'])

# 데이터 저장

****

**1. team_df를 csv 형태로 저장해봅시다.**
* Hint: to_csv, to_excel, to_json를 활용해봅시다.

In [34]:
# 아래에 코드를 작성 후 실행해 보세요
team_df.to_csv('/set_your_path/set_file_name.csv')

In [ ]:
team_df.to_csv('./set_file_name.csv')

**2. csv 파일을 열어보세요. 한글이 깨지나요?**
* Hint: pd.DataFrame의 옵션인 encoding을 CP949 또는 UTF-8로 지정해보세요

In [11]:
# 아래에 코드를 작성 후 실행해 보세요
team_df.to_csv('/set_your_path/set_file_name.csv', encoding='CP949')

# 데이터 불러오기

****

|pandas 함수|설명|
|:--:|:--:|
|read_csv()|쉼표(,)로 구분된 파일을 읽습니다.|
|read_excel()|Excel 파일을 읽습니다.|
|read_table()|탭(\t)으로 구분된 파일을 읽습니다.|
|read_fwf()|구분자가 없는 파일을 읽습니다.|

**1. 로컬에 저장된 lapis_korea.csv 파일을 불러온 후, 행 5개만 출력해보세요.**

In [2]:
# 아래에 코드를 작성 후 실행해 보세요
pd.read_csv('./datafile/lapis_korea.csv')

,Unnamed: 0,date,dateSubmitted,region,country,division,location,regionExposure,countryExposure,divisionExposure,...,sex,host,samplingStrategy,pangoLineage,nextcladePangoLineage,nextstrainClade,gisaidClade,submittingLab,originatingLab,count
0,0,2022-06-29,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.2,BA.5.2,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
1,1,2022-04-13,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.2.3,BA.2.3.8,21L,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,1
2,2,2022-04-16,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.2.3,BA.2.3,21L,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
3,3,2022-04-20,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.2,BA.2,21L,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,3
4,4,2022-03-10,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.2.3,BA.2.3,21L,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,2
5,5,2022-04-20,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.2.68,BA.2.68,21L,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,2
6,6,2022-07-17,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.2,BA.5.2,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
7,7,2022-07-27,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.2,BA.5.2,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,2
8,8,2022-02-13,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.1.1,BA.1.1,21K,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
9,9,2022-03-15,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.1.1,BA.1.1,21K,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,2
10,10,2022-03-28,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.1.1,BA.1.1,21K,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
11,11,2022-07-11,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.2,BA.5.2,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
12,12,2022-07-18,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.2.1,BA.5.2.1,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
13,13,2022-07-12,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.2.1,BA.5.2.1,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
14,14,2022-07-27,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.2.1,BA.5.2,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
15,15,2022-02-14,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.1.1,BA.1.1,21K,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,1
16,16,2022-06-30,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.2,BA.2,21L,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
17,17,2022-07-12,2023-08-14,Asia,South Korea,Seoul,NaN,Asia,South Korea,Seoul,...,NaN,Mus musculus,NaN,B.1.497,B.1.497,20C,NaN,"Seoul National University, Department of Biome...",NaN,1
18,18,2022-03-11,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.2.3,BA.2.3,21L,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,1
19,19,2022-04-05,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.2.3,BA.2.3,21L,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
20,20,2022-03-16,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.1.1,BA.1.1,21K,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,1
21,21,2022-06-23,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.5,BA.5.5,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
22,22,2022-03-27,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.2.3,BA.2.3,21L,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
23,23,2022-07-19,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.2,BA.5.2,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
24,24,2022-11-01,2023-06-20,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Mus musculus,NaN,B.1.497,B.1.497,20C,NaN,"Seoul National University, Department of Micro...",NaN,1
25,25,2022-02-10,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.1.1,BA.1.1.5,21K,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
26,26,2022-01-23,2022-12-27,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.1.1,BA.1.1,21K,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
27,27,2022-03-22,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.2.3.12,BA.2.3.12,21L,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,1
28,28,2022-03-13,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.2,BA.2,21L,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,2
29,29,2022-02-03,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.1.1,BA.1.1,21K,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
30,30,2022-07-08,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.2,BA.5.2,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
31,31,2022-03-12,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.1.1,BA.1.1,21K,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,2
32,32,2022-04-14,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.2,BA.2,21L,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
33,33,2022-10-31,2023-08-14,Asia,South Korea,Seoul,NaN,Asia,South Korea,Seoul,...,NaN,Mus musculus,NaN,B.1.497,B.1.497,20C,NaN,"Seoul National University, Department of Biome...",NaN,1
34,34,2022-07-15,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.2.1,BA.5.2.1,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
35,35,2022-07-26,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.2,BA.5.2,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,3
36,36,2022-02-16,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.1.1,BA.1.1,21K,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
37,37,2022-04-20,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.1.1,BA.1.1,21K,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,1
38,38,2022-08-01,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.2,BA.5.2,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
39,39,2022-03-14,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.1.1,BA.1.1,21K,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,1
40,40,2022-04-03,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.2.3.12,BA.2.3.12,21L,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
41,41,2022-03-14,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.2.3,BA.2.3,21L,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
42,42,2022-07-26,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.2.19,BA.5.2.19,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
43,43,2022-01-03,2022-09-01,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.1.1,BA.1.1,21K,NaN,"Seoul National University, College of Medicine",NaN,1
44,44,2022-07-07,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.2,BA.5.2,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
45,45,2022-04-01,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.2.3,BA.2.3,21L,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,2
46,46,2022-03-13,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.1.1,BA.1.1,21K,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,1
47,47,2022-03-26,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.1.1,BA.1.1,21K,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,1
48,48,2022-03-12,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.2,BA.2,21L,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,1
49,49,2022-07-25,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.2,BA.5.2,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
50,50,2022-07-13,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.2,BA.5.2,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,2
51,51,2022-03-14,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.2.3.12,BA.2.3.12,21L,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,1
52,52,2022-06-23,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.2.56,BA.2.56,21L,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
53,53,2022-04-20,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.2.3,BA.2.3,21L,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,1
54,54,2022-07-13,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.5.1.10,BA.5.1.10,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
55,55,2022-02-24,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,Homo sapiens,NaN,BA.1,BA.1,21K,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,1
56,56,2022-03-08,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,...,NaN,NaN,NaN,BA.1.1,BA.1.1,21K,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1

**2. 첫 번째 열로 지정된 csv파일에서의 index를 DataFrame에서 index로 지정해보세요.**
* Hint: index_col로 컬럼번호를 지정해보세요

In [4]:
# 아래에 코드를 작성 후 실행해 보세요
df = pd.read_csv('./datafile/lapis_korea.csv', index_col=0)

# 변수 접근

****

|접근법|예시 코드|
|:--:|:--:|
|데이터 형태 확인|df.shape|
|변수명 확인|df.columns|
|변수열 선택|df.col_names 또는df['col_names']|
|변수 삭제|del df['col_names']|
|변수명 변경|df.rename(columns={'col_names':'new_names'}, inplace=True)|

**1. lapis 데이터프레임의 행과 열 크기를 확인해보세요.**

In [6]:
# 아래에 코드를 작성 후 실행해 보세요.
df.shape

(57, 20)

**2. lapis 데이터프레임의 변수명을 확인해보세요.**

In [7]:
# 아래에 코드를 작성 후 실행해 보세요.
df.columns

Index(['date', 'dateSubmitted', 'region', 'country', 'division', 'location',
       'regionExposure', 'countryExposure', 'divisionExposure', 'age', 'sex',
       'host', 'samplingStrategy', 'pangoLineage', 'nextcladePangoLineage',
       'nextstrainClade', 'gisaidClade', 'submittingLab', 'originatingLab',
       'count'],
      dtype='object')

**3. lapis 데이터프레임의 상위 3개 행을 출력해보세요**

In [8]:
# 아래에 코드를 작성 후 실행해 보세요.
df.head(3)

,date,dateSubmitted,region,country,division,location,regionExposure,countryExposure,divisionExposure,age,sex,host,samplingStrategy,pangoLineage,nextcladePangoLineage,nextstrainClade,gisaidClade,submittingLab,originatingLab,count
0,2022-06-29,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,NaN,NaN,NaN,NaN,BA.5.2,BA.5.2,22B,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1
1,2022-04-13,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,NaN,NaN,Homo sapiens,NaN,BA.2.3,BA.2.3.8,21L,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,1
2,2022-04-16,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,NaN,NaN,NaN,NaN,BA.2.3,BA.2.3,21L,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1

**4. lapis 데이터프레임의 하위 2개 행을 출력해보세요**

In [9]:
# 아래에 코드를 작성 후 실행해 보세요.
df.tail(2)

,date,dateSubmitted,region,country,division,location,regionExposure,countryExposure,divisionExposure,age,sex,host,samplingStrategy,pangoLineage,nextcladePangoLineage,nextstrainClade,gisaidClade,submittingLab,originatingLab,count
55,2022-02-24,2022-11-14,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,NaN,NaN,Homo sapiens,NaN,BA.1,BA.1,21K,NaN,"Kangdong Sacred Heart Hospital, Hallym Univers...",NaN,1
56,2022-03-08,2022-12-28,Asia,South Korea,South Korea,NaN,Asia,South Korea,South Korea,NaN,NaN,NaN,NaN,BA.1.1,BA.1.1,21K,NaN,Jeollabukdo Institute of Health and Environmen...,NaN,1

**5. pangoLineage 변수열을 선택하여 상위 5개 행을 출력해보세요**

In [13]:
# 아래에 코드를 작성 후 실행해 보세요.

**6. country 열을 삭제해보세요**

In [55]:
# 아래에 코드를 작성 후 실행해 보세요.

**7. division 열이름을 country로 변경해보세요**

In [3]:
# 아래에 코드를 작성 후 실행해 보세요.

# 데이터 변환

****

* 데이터프레임 값의 자료형은 두 가지로 확인할 수 있습니다.
|dtypes 속성|info() 메서드|
|:--:|:--:|
|columns의 자료형만 확인 가능|세부 정보 파악 가능|

||파이썬|판다스|
|:--:|:--:|:--:|
|문자열|string|object|
|정수|int|int64|
|실수|float|float64|
|datetime|datetime|datetime64|
* 판다스와 파이썬의 자료형 표현은 상이합니다.

**아래에서 자료형 값을 출력하는 코드를 실행 후 어떤 형태의 자료형이 출력되는지 확인해보세요.**

In [11]:
# info() 메소드로 데이터프레임의 정보를 파악해보세요.
# 아래에 코드를 작성 후 실행해 보세요.
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57 entries, 0 to 56
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   57 non-null     object
 1   dateSubmitted          57 non-null     object
 2   region                 57 non-null     object
 3   country                57 non-null     object
 4   division               57 non-null     object
 5   location               0 non-null      float64
 6   regionExposure         57 non-null     object
 7   countryExposure        57 non-null     object
 8   divisionExposure       57 non-null     object
 9   age                    0 non-null      float64
 10  sex                    0 non-null      float64
 11  host                   24 non-null     object
 12  samplingStrategy       0 non-null      float64
 13  pangoLineage           57 non-null     object
 14  nextcladePangoLineage  57 non-null     object
 15  nextstrainClade        57 non-null     object
 16  gisaidClade            0 non-null      float64
 17  submittingLab          57 non-null     object
 18  originatingLab         0 non-null      float64
 19  count                  57 non-null     int64
dtypes: float64(6), int64(1), object(13)
memory usage: 9.4+ KB

**dtypes 속성으로 데이터프레임의 자료형을 확인해보세요.**

In [13]:
# 아래에 코드를 작성 후 실행해 보세요.
df.dtypes

date                      object
dateSubmitted             object
region                    object
country                   object
division                  object
location                 float64
regionExposure            object
countryExposure           object
divisionExposure          object
age                      float64
sex                      float64
host                      object
samplingStrategy         float64
pangoLineage              object
nextcladePangoLineage     object
nextstrainClade           object
gisaidClade              float64
submittingLab             object
originatingLab           float64
count                      int64
dtype: object

## **[자료형의 변경 응용 문제]**: 
데이터 포멧을 변경 후 새로운 열을 생성하기

**1. date(발병일)과 dateSubmitted(확진일)열의 포멧을 Pandas의 datetime으로 변경해보세요.**
* Hint: pd.to_datetime 함수를 활용해보세요.
* Hint: 옵션은 format='%Y-%m-%d'로 지정하면 됩니다.
* Hint: datetime 자료형으로 변경 후 새로운 열로 생성해야합니다.

In [ ]:
# 아래에 코드를 작성 후 실행해 보세요.

**2. dateSubmitted와 date의 차를 계산 후, t_days라는 새로운 열을 생성해보세요.**

In [ ]:
# 아래에 코드를 작성 후 실행해 보세요.